site_name: BLiSS

theme:
  name: readthedocs
  logo: images/logo.png

extra_css:
  - css/custom.css

plugins:
  - mkdocs-jupyter

nav:
  - GETTING STARTED: index.md

  - EXAMPLES:
      - "Vela X-1 Chandra: soft band 0.5–3 keV": notebooks/vela_x1_2001_0.5-3keV.ipynb
      - "Vela X-1 Chandra: Fe band 6–8 keV": notebooks/vela_x1_2001_6-8keV.ipynb
      - "XTE J1855-026 example": notebooks/XTE_J1855-026.ipynb

  - FUNCTIONS: functions.md
  - REFERENCES: references.md
  - CONTRIBUTE: contribute.md
